import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../dist/',import.meta.url));
test('HTML references existing local assets and has install metadata',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.match(html,/<html lang="pl"/);assert.match(html,/rel="manifest"/);for(const match of html.matchAll(/(?:src|href)="(\.\/[^"#]+)"/g))assert.ok(fs.existsSync(path.join(root,match[1])),match[1]);});
test('PWA manifest uses relative paths and real icons',()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));assert.equal(m.display,'standalone');assert.equal(m.start_url,'./');for(const icon of m.icons){const bytes=fs.readFileSync(path.join(root,icon.src));assert.equal(bytes.subarray(1,4).toString(),'PNG');const width=bytes.readUInt32BE(16);assert.equal(icon.sizes,`${width}x${width}`);}});
test('offline shell contains every executable module and each file exists',()=>{const source=fs.readFileSync(path.join(root,'sw.js'),'utf8');const files=vm.runInNewContext(source.match(/const FILES=(\[[^;]+\]);/)[1]);for(const file of files)assert.ok(fs.existsSync(path.join(root,file)),file);for(const module of ['app.js','core.js','network.js','storage.js'])assert.ok(files.includes(`./${module}`));assert.match(source,/url.origin!==self.location.origin/);});
test('no Waze/Apple Maps, no Google Routes API or Distance Matrix, and no Google API key anywhere',()=>{const app=fs.readFileSync(path.join(root,'app.js'),'utf8');const network=fs.readFileSync(path.join(root,'network.js'),'utf8');assert.doesNotMatch(app+network,/waze\.com|maps\.apple\.com|routes\.googleapis\.com|maps\.googleapis\.com|AIza|googleApiKey/);assert.doesNotMatch(app,/name="break|name="przerw/);assert.doesNotMatch(app,/Paczk om/);});
test('driving distances only ever come from the free OSRM router',()=>{const network=fs.readFileSync(path.join(root,'network.js'),'utf8');assert.match(network,/export async function fetchMatrix\(/);assert.doesNotMatch(network,/DistanceMatrixService|fetchMatrixGoogle/);});
test('GESUT layer names match the national KIUT service (water/sewage/electric/gas/heating/telecom/other)',()=>{const network=fs.readFileSync(path.join(root,'network.js'),'utf8');for(const name of ['przewod_wodociagowy','przewod_kanalizacyjny','przewod_elektroenergetyczny','przewod_gazowy','przewod_cieplowniczy','przewod_telekomunikacyjny'])assert.match(network,new RegExp(name));});
test('day-optimize and day-reset actions are wired up, reset asks for confirmation',()=>{const app=fs.readFileSync(path.join(root,'app.js'),'utf8');assert.match(app,/case 'optimize-day':await optimizeDayOrder\(selectedDay\)/);assert.match(app,/case 'reset-day':await resetDay\(selectedDay\)/);const resetFn=app.slice(app.indexOf('async function resetDay'),app.indexOf('async function resetDay')+400);assert.match(resetFn,/confirm\(/);});
test('the work-map base layer picker offers all five requested sources, each with its own thumbnail',()=>{const app=fs.readFileSync(path.join(root,'app.js'),'utf8');for(const id of ['osm','esri','orto','google-hybrid','google'])assert.ok(app.includes(`id:'${id}'`),`missing base layer ${id}`);assert.match(app,/function baseLayerThumbUrl/);assert.match(app,/function makeBaseTileLayer/);});
test('base layer picker sits above the map as plain HTML, not floating on top of it',()=>{const app=fs.readFileSync(path.join(root,'app.js'),'utf8');const workMapIdx=app.indexOf(`id="work-map"`),pickerIdx=app.indexOf('class="map-base-picker"');assert.ok(pickerIdx>=0&&pickerIdx<workMapIdx,'picker markup must come before the map canvas in the DOM');assert.doesNotMatch(app,/L\.control\(\{position:'topleft'\}\)/);});
test('the auto-distribute module has been removed entirely',()=>{const app=fs.readFileSync(path.join(root,'app.js'),'utf8');const core=fs.readFileSync(path.join(root,'core.js'),'utf8');assert.doesNotMatch(app+core,/autoDistribute|auto-distribute|Zaproponuj rozkład/);});
test('optimize-route is a primary, always-visible top action for the week view',()=>{const app=fs.readFileSync(path.join(root,'app.js'),'utf8');const topActionsIdx=app.indexOf("view==='week'?`<div class=\"top-actions\">");const topActionsBlock=app.slice(topActionsIdx,topActionsIdx+700);assert.match(topActionsBlock,/data-act="optimize-day"/);assert.match(topActionsBlock,/class="primary" data-act="optimize-day"/);});
test('an entire import can be deleted, with confirmation, removing only its own jobs',()=>{const app=fs.readFileSync(path.join(root,'app.js'),'utf8');assert.match(app,/case 'delete-import':await deleteImport\(id\)/);const fn=app.slice(app.indexOf('async function deleteImport'),app.indexOf('async function deleteImport')+400);assert.match(fn,/confirm\(/);const core=fs.readFileSync(path.join(root,'core.js'),'utf8');assert.match(core,/export function removeImport/);});
test('parcels (działki) can be toggled on the work map, identified by click via ULDK, with a distinct base layer for boundaries',()=>{
  const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
  const network=fs.readFileSync(path.join(root,'network.js'),'utf8');
  const core=fs.readFileSync(path.join(root,'core.js'),'utf8');
  assert.match(app,/data-parcels="1"/);
  assert.match(app,/function toggleParcelsLayer/);
  assert.match(app,/workMap\.on\('click'/);
  assert.match(network,/export async function findParcelAt/);
  assert.match(core,/export function parseParcelWkt/);
});
test('a visit under 20 minutes from another gets a very visible proximity warning, in both the day list and the candidate list',()=>{
  const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
  assert.match(app,/function proximityWarning/);
  const seconds=app.match(/return best&&best\.seconds<(\d+)\?best:null/);
  assert.ok(seconds&&Number(seconds[1])===1200,'threshold must be 20 minutes (1200s)');
  const stopFn=app.slice(app.indexOf('function renderStop'),app.indexOf('function renderCandidate'));
  const candidateFn=app.slice(app.indexOf('function renderCandidate'),app.indexOf('function renderAddSection'));
  assert.match(stopFn,/near\?`<span class="tag red">/);
  assert.match(candidateFn,/tag red/);
});
test('each day of the week has its own colour, used for the map route/pins and echoed on its tile',()=>{
  const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
  const match=app.match(/const DAY_COLORS=\[([^\]]+)\]/);
  assert.ok(match);
  const colors=match[1].split(',').map(s=>s.trim().replace(/'/g,''));
  assert.equal(colors.length,7);
  assert.equal(new Set(colors).size,7,'all seven day colours must be distinct');
  assert.match(app,/--day-color:\$\{DAY_COLORS\[day\]\}/);
  const styles=fs.readFileSync(path.join(root,'styles.css'),'utf8');
  for(let i=0;i<7;i++)assert.match(styles,new RegExp(`\\.map-pin\\.day${i}\\{`));
});
test('only the five weekdays are plannable — no Saturday/Sunday tab, and nothing left over from them can be silently lost',()=>{
  const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
  const match=app.match(/const ALL_DAYS=\[([^\]]+)\]/);
  assert.ok(match);
  assert.deepEqual(match[1].split(',').map(s=>Number(s.trim())),[0,1,2,3,4]);
  assert.doesNotMatch(app,/day-grid seven/);
  assert.match(app,/function placedVisitIds\(\)\{return new Set\(Object\.entries\(currentPlan\(\)\?\.routes\|\|\{\}\)\.filter\(\(\[d\]\)=>ALL_DAYS\.includes\(Number\(d\)\)\)/);
  assert.match(app,/ALL_DAYS\.map\(i=>`<option value="\$\{i\}"/,'move-visit dropdown must only offer weekdays');
});
test('the "add a stop" candidate list caps at a handful of cards with a show-more toggle, instead of unfolding the whole pool',()=>{
  const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
  assert.match(app,/const CANDIDATE_LIMIT=5/);
  assert.match(app,/case 'show-more-candidates':addSectionExpanded=true/);
  assert.match(app,/case 'show-fewer-candidates':addSectionExpanded=false/);
  const fn=app.slice(app.indexOf('function renderAddSection'),app.indexOf('function importDrop'));
  assert.match(fn,/Math\.min\(CANDIDATE_LIMIT,items\.length\)/);
  assert.match(fn,/data-act="show-more-candidates"/);
});
test('"Zobacz miejsce pracy" is compact — one chip row for parcels+GESUT layers (not a multi-row checkbox grid), Street View as a small icon button',()=>{
  const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
  const styles=fs.readFileSync(path.join(root,'styles.css'),'utf8');
  const fn=app.slice(app.indexOf('function showWorkMap'),app.indexOf('function drawWorkMap'));
  assert.match(fn,/class="chip-row" id="work-layers"/);
  assert.match(fn,/class="icon-btn streetview-link"/);
  assert.doesNotMatch(app,/class="layer-toggles"/);
  assert.match(styles,/\.chip-row\{/);
  assert.match(styles,/\.icon-btn\{/);
});
