import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../dist/',import.meta.url));
test('HTML references existing local assets and has install metadata',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.match(html,/<html lang="pl"/);assert.match(html,/rel="manifest"/);for(const match of html.matchAll(/(?:src|href)="(\.\/[^"#]+)"/g))assert.ok(fs.existsSync(path.join(root,match[1])),match[1]);});
test('PWA manifest uses relative paths and real icons',()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));assert.equal(m.display,'standalone');assert.equal(m.start_url,'./');for(const icon of m.icons){const bytes=fs.readFileSync(path.join(root,icon.src));assert.equal(bytes.subarray(1,4).toString(),'PNG');const width=bytes.readUInt32BE(16);assert.equal(icon.sizes,`${width}x${width}`);}});
test('offline shell contains every executable module and each file exists',()=>{const source=fs.readFileSync(path.join(root,'sw.js'),'utf8');const files=vm.runInNewContext(source.match(/const FILES=(\[[^;]+\]);/)[1]);for(const file of files)assert.ok(fs.existsSync(path.join(root,file)),file);for(const module of ['app.js','core.js','network.js','storage.js'])assert.ok(files.includes(`./${module}`));assert.match(source,/url.origin!==self.location.origin/);});
test('no Waze/Apple Maps, no Google Routes API, and no hardcoded Google API key',()=>{const app=fs.readFileSync(path.join(root,'app.js'),'utf8');const network=fs.readFileSync(path.join(root,'network.js'),'utf8');assert.doesNotMatch(app+network,/waze\.com|maps\.apple\.com|routes\.googleapis\.com|AIza/);assert.doesNotMatch(app,/name="break|name="przerw/);assert.doesNotMatch(app,/Paczk om/);});
test('Google Distance Matrix is opt-in: only called when the user supplied their own key',()=>{const network=fs.readFileSync(path.join(root,'network.js'),'utf8');assert.match(network,/if\(!apiKey\)throw new Error/);const app=fs.readFileSync(path.join(root,'app.js'),'utf8');assert.match(app,/settings\.googleApiKey/);});
test('a shared plan copy never carries the sender\'s Google API key to another device',()=>{const app=fs.readFileSync(path.join(root,'app.js'),'utf8');const exportFn=app.slice(app.indexOf('async function exportPlan'),app.indexOf('async function exportPlan')+400);assert.match(exportFn,/googleApiKey:''/);});
